version: '3'
services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "testejavadb"
    ports:
      - "3306:3306"
    volumes:
      - ./volumes:/var/lib/mysql
    networks:
      - mysql-compose-network
networks:
  mysql-compose-network:
    driver: bridge